import { Routes } from '@angular/router';
import { Home } from './features/home/home';
import { About } from './features/about/about';
import { Outlets } from './features/outlets/outlets';
import { HearingTest } from './features/hearing-test/hearing-test';
import { Products } from './features/products/products';
import { Services } from './features/services/services';
import { Blog } from './features/blog/blog';
import { Compare } from './features/compare/compare';
import { Cart } from './features/cart/cart';
import { Checkout } from './features/checkout/checkout';
import { OrderSuccess } from './features/order-success/order-success';
import { PrivacyPolicy } from './features/legal/privacy-policy/privacy-policy';
import { TermsOfService } from './features/legal/terms-of-service/terms-of-service';
import { MedicalDisclaimer } from './features/legal/medical-disclaimer/medical-disclaimer';
import { ProductDetail } from './features/product-detail/product-detail';
import { Wishlist } from './features/wishlist/wishlist';
import { Payment } from './features/payment/payment';
import { PaymentSuccess } from './features/payment/payment-success';
import { PaymentFailure } from './features/payment/payment-failure';
import { Login } from './features/login/login';
import { Profile } from './features/profile/profile';
import { ForgotPassword } from './features/login/forgot-password';
import { Gallery } from './features/gallery/gallery';

export const routes: Routes = [
    { path: '', component: Home },
    { path: 'about', component: About },
    { path: 'gallery', component: Gallery },
    { path: 'login', component: Login },
    { path: 'forgot-password', component: ForgotPassword },
    { path: 'profile', component: Profile },

    { path: 'outlets', component: Outlets },
    { path: 'hearing-test', component: HearingTest },
    { path: 'products', component: Products },
    { path: 'products/:id', component: ProductDetail },
    { path: 'services', component: Services },
    { path: 'blog', component: Blog },
    { path: 'compare', component: Compare },
    { path: 'cart', component: Cart },
    { path: 'wishlist', component: Wishlist },
    { path: 'checkout', component: Checkout },
    { path: 'payment', component: Payment },
    { path: 'payment/success', component: PaymentSuccess },
    { path: 'payment/failure', component: PaymentFailure },
    { path: 'order-success', component: OrderSuccess },
    { path: 'privacy-policy', component: PrivacyPolicy },
    { path: 'terms-of-service', component: TermsOfService },
    { path: 'medical-disclaimer', component: MedicalDisclaimer }
];
